# Generated by Django 2.2 on 2023-04-01 18:34

from django.db import migrations

def populate_data(apps, schema_editor):
    MyModel = apps.get_model('doghub_app', 'Tag')
    MyModel.objects.create(tag_name="Dog-Owner",tag_type="U")

class Migration(migrations.Migration):

    dependencies = [
        ('doghub_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]

